top artists and top songs are now clickable/navigate to respective so…
cis3296f24/MusicMatcher pull request #23
Opened 2024-12-01 17:13 UTC by NeverEverFelix

…ng/artist page

2024-12-01 17:15 UTC, yuseftohamy approved these changes

2024-12-01 17:16 UTC, yuseftohamy approved these changes

2024-12-01 17:17 UTC, yuseftohamy requested changes
Fix conflicts

2024-12-03 02:23 UTC, closed without merging

2024-12-03 02:23 UTC, efiera commented
deprecated